server:
  port: 0

spring:
  application:
    name: article-service

  datasource:
    url: jdbc:mysql://localhost:3306/scene?serverTimezone=Asia/Seoul
    username: root
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  jwt:
    secret: ${spring.jwt.secret}

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  data:
    redis:
      host: localhost
      port: 6379

naver:
  client-id: ${naver.client-id}
  client-secret: ${naver.client-secret}

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.articleservice.Scheduler: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh