server:
  port: 0

spring:
  application:
    name: sentiment-service

  datasource:
    url: jdbc:mysql://mysql:3306/scene?serverTimezone=Asia/Seoul
    username: root
    password: ${spring.datasource.password}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  jwt:
    secret: ${spring.jwt.secret}

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

openai:
  api-key: ${openai.api-key}
  model: gpt-3.5-turbo-16k

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh

logging:
  level:
    com.example.sentimentservcie: DEBUG