server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kdhdd/msa-config
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh